{
    "spec": {
        "template": {
            "spec": {
                "containers": [{
                    "name": "4linux-php-sha256-1",
                    "volumeMounts": [{
                        "mountPath": "/app",
                        "name": "php-volume"
                    }]
                }],
                "volumes": [{
                    "name": "php-volume",
                    "persistentVolumeClaim": {
                        "claimName": "volume-claim-php-nfs"
                    }
                }]
            }
        }
    }
}              
